---
title: "Confounding effect of categorical variables"
output:
  html_document:
    df_print: paged
---

# Import Libraries

```{r message=FALSE, libs}
library(dplyr)
library(tidyverse)
library(data.table)
library(ggplot2)
library(raster)
```

# Define the data generating process

```{r generating data}
set.seed(1)

# confounding effect
df <- data.frame(gene = sample(c(0,1), size = 1000, replace = TRUE))

# base treatment probability
treat_probs <- rnorm(1000, mean = 0.5, sd = 0.1)
gt_effects <- rnorm(1000, mean = 0.25, sd = 0.05) # gene effect on treatment / selection bias
treat_probs <- (treat_probs + (gt_effects*df$gene)) %>%
  clamp(lower = 0, upper = 1, useValues = TRUE)
# create gene column based on probabilities
df$treatment <- treat_probs %>% sapply(function(x) {
  sample(c(0,1), size = 1, replace = TRUE, prob = c(1-x,x))
})

# base survival probability
survive_probs <- rnorm(1000, mean = 0.5, sd = 0.15)
ts_effects <- rnorm(1000, mean = 0.05, sd = 0.05) # negative treatment effect on survivial
gs_effects <- rnorm(1000, mean = 0.3, sd = 0.05) # gene effect on survival
survive_probs <- (survive_probs - (ts_effects*df$treatment) + (gs_effects*df$gene)) %>%
  clamp(lower = 0, upper = 1, useValues = TRUE)
df$survive <- survive_probs %>% sapply(function(x) {
  sample(c(0,1), size = 1, replace = TRUE, prob = c(1-x,x))
})
```

# Results

```{r simpsons paradox}
df %>% group_by(treatment) %>%
  summarize(recovery_rate = mean(survive))

df %>% group_by(treatment, gene) %>%
  summarize(count = n(), recovery_rate = mean(survive))
```

Simpson's paradox: treatment effect seems positive when the `gene` variable was omitted.

```{r logit model}
logit <- glm(survive ~ treatment + gene, family = "binomial", data = df)

summary(logit)
```

