---
title: "Unaccounted variance and mixed model"
output:
  html_document:
    df_print: paged
---

# Import Libraries

```{r message=FALSE, libs}
library(tidyverse)
library(raster)

library(lme4)
library(lmerTest)
```

# Subject-wise variation with t-test

```{r}
set.seed(8376)

subject.num <- 100 # number of units/subjects

study.n <- 100 # number of replicated studies

confint.results <- data.frame(study.id = 1:study.n)
lower.results <- rep(0, study.n)
upper.results <- rep(0, study.n)
estimates <- rep(0, study.n)

wihtin.vector <- c(20, 50, 100) # within sample size
for (n in wihtin.vector) {

  for (i in 1:study.n) {
    subj.intercepts <- runif(subject.num, 5, 15)
    subj.slopes <- rnorm(subject.num, mean = 0, sd = 5)
    
    y <- c()
    treat.vector <- c()
    for (j in 1:subject.num) {
      treat <- sample(c(0,1), size = n, replace = TRUE) # treatment assignment
      y.tmp <- subj.slopes[j]*treat + subj.intercepts[j] + rnorm(n, mean = 0, sd = 1)
      
      treat.vector <- c(treat.vector, treat)
      y <- c(y, y.tmp)
    }
    subj.id <- rep(1:subject.num, each = n)
    
    data <- data.frame(subj_id = subj.id, treat = treat.vector, y = y)
    
    group1 <- data %>%
      filter(treat == 0)
    group2 <- data %>%
      filter(treat == 1)
    
    result <- t.test(group2$y, group1$y) # equivalent of fixed effect OLS
    lower.results[i] <- result$conf.int[1]
    upper.results[i] <- result$conf.int[2]
    estimates[i] <- result$estimate[["mean of x"]] - result$estimate[["mean of y"]]
  }
  
  confint.results$lower <- lower.results
  confint.results$upper <- upper.results
  confint.results$estimate <- estimates
  confint.results <- confint.results %>%
    mutate(contain_param = ifelse(lower <= 0 & upper >= 0, TRUE, FALSE))
  
  meta_avg_effect <- mean(confint.results$estimate)
  
  g <- confint.results %>%
    ggplot(aes(x=estimate, y = reorder(study.id, estimate))) +
    geom_point(size = 1) +
    geom_errorbar(aes(xmin=lower, xmax=upper, col=contain_param), width=.1) +
    geom_vline(xintercept = 0, col = "red") +
    ggtitle(paste0("within sample size = ", n)) +
    theme(axis.title.y=element_blank(),
          axis.text.y=element_blank(),
          axis.ticks.y=element_blank())
  
  #ggsave(file.path("img", paste0("add_var_n", n, ".png")))
  print(g)
}
```

# No slope variance

```{r}
subject.num <- 100

study.n <- 100

confint.results <- data.frame(study.id = 1:study.n)
lower.results <- rep(0, study.n)
upper.results <- rep(0, study.n)
estimates <- rep(0, study.n)

n <- 50 # within sample size

for (i in 1:study.n) {
  subj.intercepts <- runif(subject.num, 5, 15)
  slope <- 0
  
  y <- c()
  treat.vector <- c()
  for (j in 1:subject.num) {
    treat <- sample(c(0,1), size = n, replace = TRUE) # treatment assignment
    y.tmp <- treat*slope + subj.intercepts[j] + rnorm(n, mean = 0, sd = 1)
    
    treat.vector <- c(treat.vector, treat)
    y <- c(y, y.tmp)
  }
  subj.id <- rep(1:subject.num, each = n)
  
  data <- data.frame(subj_id = subj.id, treat = treat.vector, y = y)
  
  group1 <- data %>%
    filter(treat == 0)
  group2 <- data %>%
    filter(treat == 1)
  
  result <- t.test(group2$y, group1$y)
  lower.results[i] <- result$conf.int[1]
  upper.results[i] <- result$conf.int[2]
  estimates[i] <- result$estimate[["mean of x"]] - result$estimate[["mean of y"]]
}

confint.results$lower <- lower.results
confint.results$upper <- upper.results
confint.results$estimate <- estimates
confint.results <- confint.results %>%
  mutate(contain_param = ifelse(lower <= 0 & upper >= 0, TRUE, FALSE))

meta_avg_effect <- mean(confint.results$estimate)

g <- confint.results %>%
  ggplot(aes(x=estimate, y = reorder(study.id, estimate))) +
  geom_point(size = 1) +
  geom_errorbar(aes(xmin=lower, xmax=upper, col=contain_param), width=.1) +
  geom_vline(xintercept = 0, col = "red") +
  ggtitle(paste0("within sample size = ", n)) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

#ggsave(file.path("img", paste0("null_model.png")))
print(g)
```

# Mixed effect model

```{r}
subject.num <- 100

study.n <- 100

confint.results <- data.frame(study.id = 1:study.n)
lower.results <- rep(0, study.n)
upper.results <- rep(0, study.n)
estimates <- rep(0, study.n)

n <- 50 # within sample size

for (i in 1:study.n) {
  subj.intercepts <- runif(subject.num, 5, 15)
  subj.slopes <- rnorm(subject.num, mean = 0, sd = 5)
  
  y <- c()
  treat.vector <- c()
  for (j in 1:subject.num) {
    treat <- sample(c(0,1), size = n, replace = TRUE) # treatment assignment
    y.tmp <- subj.slopes[j]*treat + subj.intercepts[j] + rnorm(n, mean = 0, sd = 1)
    
    treat.vector <- c(treat.vector, treat)
    y <- c(y, y.tmp)
  }
  subj.id <- rep(1:subject.num, each = n)
  
  data <- data.frame(subj_id = subj.id, treat = treat.vector, y = y)
  
  mixed.lmer <- lmer(y ~ treat + (1 + treat|subj_id), data = data)
  
  # summary(mixed.lmer)
  # ranef(mixed.lmer)
  test.result <- contest1D(mixed.lmer, c(0,1), confint = TRUE)
  
  lower.results[i] <- test.result$lower
  upper.results[i] <- test.result$upper
  estimates[i] <- test.result$Estimate
}

confint.results$lower <- lower.results
confint.results$upper <- upper.results
confint.results$estimate <- estimates
confint.results <- confint.results %>%
  mutate(contain_param = ifelse(lower <= 0 & upper >= 0, TRUE, FALSE))

meta_avg_effect <- mean(confint.results$estimate)

g <- confint.results %>%
  ggplot(aes(x=estimate, y = reorder(study.id, estimate))) +
  geom_point(size = 1) +
  geom_errorbar(aes(xmin=lower, xmax=upper, col=contain_param), width=.1) +
  geom_vline(xintercept = 0, col = "red") +
  ggtitle(paste0("within sample size = ", n)) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

#ggsave(file.path("img", paste0("mixed_model_confints.png")))
print(g)
```