---
title: "Incorrectly specified model with simplified tests"
output:
  html_document:
    df_print: paged
---

# Import Libraries

```{r message=FALSE, libs}
library(dplyr)
library(tidyverse)
library(data.table)
library(ggplot2)
library(raster)
```

# Additional variation

```{r}
level.num <- 50
sublevels <- 1:level.num

study.n <- 100

confint.results <- data.frame(study.id = 1:study.n)
lower.results <- rep(0, study.n)
upper.results <- rep(0, study.n)
estimates <- rep(0, study.n)

n.vector <- c(1000, 2500, 5000)
for (n in n.vector) {

  for (i in 1:study.n) {
    subintercepts <- runif(level.num, 5, 15)
    subslopes <- rnorm(level.num, mean = 0, sd = 5)
    
    sl <- sample(sublevels, size = n, replace = TRUE)
    group <- sample(c(0,1), size = n, replace = TRUE)
    y <- sapply(1:n, function(i) {
      return(subslopes[sl[i]]*group[i] + subintercepts[sl[i]])
    }) + rnorm(n, mean = 0, sd = 1)
    
    data <- data.frame(group, sl, y)
    
    group1 <- data %>%
      filter(group == 0)
    group2 <- data %>%
      filter(group == 1)
    
    result <- t.test(group2$y, group1$y)
    lower.results[i] <- result$conf.int[1]
    upper.results[i] <- result$conf.int[2]
    estimates[i] <- result$estimate[["mean of x"]] - result$estimate[["mean of y"]]
  }
  
  confint.results$lower <- lower.results
  confint.results$upper <- upper.results
  confint.results$estimate <- estimates
  
  meta_avg_effect <- mean(confint.results$estimate)
  
  confint.results %>%
    ggplot(aes(x=estimate, y = reorder(study.id, estimate))) +
    geom_point(size = 1) +
    geom_errorbar(aes(xmin=lower, xmax=upper), width=.1) +
    geom_vline(xintercept = 0, col = "red") +
    ggtitle(paste0("n = ", n)) +
    theme(axis.title.y=element_blank(),
          axis.text.y=element_blank(),
          axis.ticks.y=element_blank())
  
  ggsave(file.path("img", paste0("add_var_n", n, ".png")))
}
```

# Unadjusted model

```{r generating data}
study.n <- 100

confint.results <- data.frame(study.id = 1:study.n)
lower.results <- rep(0, study.n)
upper.results <- rep(0, study.n)
estimates <- rep(0, study.n)

for (i in 1:study.n) {
  n <- 1000
  u1 <- runif(n, -2, 2)
  w <- -2*u1 + rnorm(n, mean = 0, sd = 1)
  r <- 1.2*u1 + rnorm(n, mean = 0, sd = 1)
  t <- rnorm(n, mean = 3, sd = 1.5)
  group_scores <- 1.5*w + (-0.2)*r + 2*t + rnorm(n, mean = 0, sd = 1)
  group_probs <- exp(group_scores)/sum(exp(group_scores))
  group1_inds <- sample(1:n, size = n/2, replace = FALSE, prob = group_probs)
  group <- rep(0, n)
  group[group1_inds] <- 1
  
  y <- -0.6*w + (-1.5)*r + 3*t + rnorm(n, mean = 0, sd = 1)
  data <- data.frame(group, y, t, r, w)
  group1 <- data %>%
    filter(group == 0)
  group2 <- data %>%
    filter(group == 1)
  
  result <- t.test(group2$y, group1$y)
  lower.results[i] <- result$conf.int[1]
  upper.results[i] <- result$conf.int[2]
  estimates[i] <- result$estimate[["mean of x"]] - result$estimate[["mean of y"]]
}

confint.results$lower <- lower.results
confint.results$upper <- upper.results
confint.results$estimate <- estimates

meta_avg_effect <- mean(confint.results$estimate)

ggplot(data = confint.results, aes(x=estimate, y = study.id)) +
  geom_point(size = 1) +
  geom_errorbar(aes(xmin=lower, xmax=upper), width=.1) +
  geom_vline(xintercept = 0, col = "red") +
  geom_vline(xintercept = meta_avg_effect, col = "blue")
```